export const SET_START_POSITION_X = 'SET_START_POSITION_X';
export const SET_START_POSITION_Y = 'SET_START_POSITION_Y';
export const SPACESHIP_MOVE_UP    = 'SPACESHIP_MOVE_UP';
export const SPACESHIP_MOVE_DOWN  = 'SPACESHIP_MOVE_DOWN';
export const SPACESHIP_MOVE_RIGHT = 'SPACESHIP_MOVE_RIGHT';
export const SPACESHIP_MOVE_LEFT  = 'SPACESHIP_MOVE_LEFT';